//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATM.Util.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATM.Util.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string Application_Language {
            get {
                return ResourceManager.GetString("Application.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string Button_Height {
            get {
                return ResourceManager.GetString("Button.Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string Button_Length {
            get {
                return ResourceManager.GetString("Button.Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string Customer_IdleTime_ToLogout {
            get {
                return ResourceManager.GetString("Customer.IdleTime.ToLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string Customer_Logsin {
            get {
                return ResourceManager.GetString("Customer.Logsin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Customer_MaxFailedLoginAttempt {
            get {
                return ResourceManager.GetString("Customer.MaxFailedLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string Customer_Password_Length_Max {
            get {
                return ResourceManager.GetString("Customer.Password.Length.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Customer_Password_Length_Min {
            get {
                return ResourceManager.GetString("Customer.Password.Length.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string Customer_Username_length {
            get {
                return ResourceManager.GetString("Customer.Username.length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string DataAccessLayer_ConnectionFactory {
            get {
                return ResourceManager.GetString("DataAccessLayer.ConnectionFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eager.
        /// </summary>
        internal static string DataAccessLayer_LoadMode {
            get {
                return ResourceManager.GetString("DataAccessLayer.LoadMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL.
        /// </summary>
        internal static string DataAccessLayer_Mode {
            get {
                return ResourceManager.GetString("DataAccessLayer.Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataAccessLayer_Password {
            get {
                return ResourceManager.GetString("DataAccessLayer.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataAccessLayer_Server {
            get {
                return ResourceManager.GetString("DataAccessLayer.Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataAccessLayer_Url {
            get {
                return ResourceManager.GetString("DataAccessLayer.Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataAccessLayer_Username {
            get {
                return ResourceManager.GetString("DataAccessLayer.Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Transaction_EftFee {
            get {
                return ResourceManager.GetString("Transaction.EftFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string Validator_Password_Max {
            get {
                return ResourceManager.GetString("Validator.Password.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Validator_Password_Min {
            get {
                return ResourceManager.GetString("Validator.Password.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string Validator_Username_Max {
            get {
                return ResourceManager.GetString("Validator.Username.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Validator_Username_Min {
            get {
                return ResourceManager.GetString("Validator.Username.Min", resourceCulture);
            }
        }
    }
}
